import mutations from "./mutations";
import actions from "./actions";
import getters from "./getters";

export default {
  state() {
    return {
      competetions: [
        {
          id: 61,
          name: "Ligue 1",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/61.png",
          code: "FR",
          flag: "https://media.api-sports.io/flags/fr.svg",
        },
        {
          id: 62,
          name: "Ligue 2",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/62.png",
          code: "FR",
          flag: "https://media.api-sports.io/flags/fr.svg",
        },
        {
          id: 39,
          name: "Premier League",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          code: "GB",
          flag: "https://media.api-sports.io/flags/gb.svg",
        },
        {
          id: 40,
          name: "Championship",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/40.png",
          code: "GB",
          flag: "https://media.api-sports.io/flags/gb.svg",
        },
        {
          id: 46,
          name: "EFL Trophy",
          type: "Cup",
          logo: "https://media.api-sports.io/football/leagues/46.png",
          code: "GB",
          flag: "https://media.api-sports.io/flags/gb.svg",
        },
        {
          id: 45,
          name: "FA Cup",
          type: "Cup",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          code: "GB",
          flag: "https://media.api-sports.io/flags/gb.svg",
        },
        {
          id: 78,
          name: "Bundesliga 1",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/78.png",
          code: "DE",
          flag: "https://media.api-sports.io/flags/de.svg",
        },
        {
          id: 79,
          name: "Bundesliga 2",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/79.png",
          code: "DE",
          flag: "https://media.api-sports.io/flags/de.svg",
        },
        {
          id: 81,
          name: "DFB Pokal",
          type: "Cup",
          logo: "https://media.api-sports.io/football/leagues/81.png",
          code: "DE",
          flag: "https://media.api-sports.io/flags/de.svg",
        },
        {
          id: 135,
          name: "Serie A",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/135.png",
          code: "IT",
          flag: "https://media.api-sports.io/flags/it.svg",
        },
        {
          id: 136,
          name: "Serie B",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/136.png",
          code: "IT",
          flag: "https://media.api-sports.io/flags/it.svg",
        },
        {
          id: 137,
          name: "Coppa Italia",
          type: "Cup",
          logo: "https://media.api-sports.io/football/leagues/137.png",
          code: "IT",
          flag: "https://media.api-sports.io/flags/it.svg",
        },
        {
          id: 88,
          name: "Eredivisie",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/88.png",
          code: "NL",
          flag: "https://media.api-sports.io/flags/nl.svg",
        },
        {
          id: 140,
          name: "Primera Division",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/140.png",
          code: "ES",
          flag: "https://media.api-sports.io/flags/es.svg",
        },
        {
          id: 141,
          name: "Segunda Division",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/141.png",
          code: "ES",
          flag: "https://media.api-sports.io/flags/es.svg",
        },
      ],
    };
  },
  mutations,
  actions,
  getters,
};
