import mutations from "./mutations";
import actions from "./actions";
import getters from "./getters";

export default {
  state() {
    return {
      competetions: [
        {
          id: 2015,
          name: "Ligue 1",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/61.png",
          code: "FRA",
          flag: "https://media.api-sports.io/flags/fr.svg",
        },
        {
          id: 2142,
          name: "Ligue 2",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/62.png",
          code: "FRA",
          flag: "https://media.api-sports.io/flags/fr.svg",
        },
        {
          id: 2021,
          name: "Premier League",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          code: "ENG",
          flag: "https://media.api-sports.io/flags/gb.svg",
        },
        {
          id: 2016,
          name: "Championship",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/40.png",
          code: "ENG",
          flag: "https://media.api-sports.io/flags/gb.svg",
        },
        {
          id: 46,
          name: "EFL Trophy",
          type: "Cup",
          logo: "https://media.api-sports.io/football/leagues/46.png",
          code: "ENG",
          flag: "https://media.api-sports.io/flags/gb.svg",
        },
        {
          id: 2055,
          name: "FA Cup",
          type: "Cup",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          code: "ENG",
          flag: "https://media.api-sports.io/flags/gb.svg",
        },
        {
          id: 2002,
          name: "Bundesliga 1",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/78.png",
          code: "DEU",
          flag: "https://media.api-sports.io/flags/de.svg",
        },
        {
          id: 2004,
          name: "Bundesliga 2",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/79.png",
          code: "DEU",
          flag: "https://media.api-sports.io/flags/de.svg",
        },
        {
          id: 2011,
          name: "DFB Pokal",
          type: "Cup",
          logo: "https://media.api-sports.io/football/leagues/81.png",
          code: "DEU",
          flag: "https://media.api-sports.io/flags/de.svg",
        },
        {
          id: 2019,
          name: "Serie A",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/135.png",
          code: "ITA",
          flag: "https://media.api-sports.io/flags/it.svg",
        },
        {
          id: 2121,
          name: "Serie B",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/136.png",
          code: "ITA",
          flag: "https://media.api-sports.io/flags/it.svg",
        },
        {
          id: 2122,
          name: "Coppa Italia",
          type: "Cup",
          logo: "https://media.api-sports.io/football/leagues/137.png",
          code: "ITA",
          flag: "https://media.api-sports.io/flags/it.svg",
        },
        {
          id: 2003,
          name: "Eredivisie",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/88.png",
          code: "NLD",
          flag: "https://media.api-sports.io/flags/nl.svg",
        },
        {
          id: 2014,
          name: "Primera Division",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/140.png",
          code: "ESP",
          flag: "https://media.api-sports.io/flags/es.svg",
        },
        {
          id: 2077,
          name: "Segunda Division",
          type: "League",
          logo: "https://media.api-sports.io/football/leagues/141.png",
          code: "ESP",
          flag: "https://media.api-sports.io/flags/es.svg",
        },
      ],
    };
  },
  mutations,
  actions,
  getters,
};
